import type { ActionService } from '../infra/action'

export class SoundService implements ActionService {
  // Require manual testing

  trigger(): void {
    // TODO: If this project involve commercial use in future, replace this with other sound.
    // Currently, this sound is generated by https://elevenlabs.io/app/sound-effects in a free user account
    // But its license limit free user to use it for non-commercial use only.
    new Audio(chrome.runtime.getURL('notification.mp3')).play()
  }
}
