/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
  }
  export interface ComponentCustomProperties {
    vBToggle: typeof import('bootstrap-vue-next/directives/BToggle')['vBToggle']
  }
}
