import { StorageInterface } from '@zero-in/shared/infra/storage/interface'
import { LocalStorageWrapper } from '@zero-in/shared/infra/storage/local-storage/index'
import { newLocalStorage } from './storage/local-storage'

export type DebugLogEntry = { at: string; event: string } & Record<string, unknown>

/**
 * Ring buffer of diagnostic events persisted in local storage so that it survives service worker restarts.
 * Read it from the service worker console with:
 *   chrome.storage.local.get('debugLog', (r) => console.table(r.debugLog))
 */

// TODO: This class is generated by claude and not fully covered by tests. Either delete it or improve it in future.
export class DebugLog {
  static readonly STORAGE_KEY = 'debugLog'
  static readonly DEFAULT_MAX_ENTRIES = 300

  static create() {
    return new DebugLog({ storage: newLocalStorage(), mirrorToConsole: true })
  }

  static createFake({ maxEntries = DebugLog.DEFAULT_MAX_ENTRIES } = {}) {
    return new DebugLog({ storage: LocalStorageWrapper.createFake(), maxEntries })
  }

  private pending: Promise<void> = Promise.resolve()

  constructor(
    private deps: { storage: StorageInterface; maxEntries?: number; mirrorToConsole?: boolean }
  ) {}

  log(event: string, data: Record<string, unknown> = {}) {
    const entry: DebugLogEntry = { at: new Date().toISOString(), event, ...data }
    if (this.deps.mirrorToConsole) {
      console.debug('[zero-in]', entry)
    }
    this.pending = this.pending
      .then(() => this.append(entry))
      .catch((err) => {
        console.error('DebugLog append failed', err)
      })
  }

  async getEntries(): Promise<DebugLogEntry[]> {
    await this.pending
    return (await this.deps.storage.get(DebugLog.STORAGE_KEY)) ?? []
  }

  private async append(entry: DebugLogEntry) {
    const entries: DebugLogEntry[] = (await this.deps.storage.get(DebugLog.STORAGE_KEY)) ?? []
    entries.push(entry)
    const maxEntries = this.deps.maxEntries ?? DebugLog.DEFAULT_MAX_ENTRIES
    await this.deps.storage.set(DebugLog.STORAGE_KEY, entries.slice(-maxEntries))
  }
}
