name: Extension Continuous Integration

on:
  push:
    branches-ignore:
      - main # Because "Require branches to be up to date before merging" is enabled for main. The checking will be completed before pull request can be merged.
    paths:
      - 'extension/**'
  pull_request:
    branches:
      - main
    paths:
      - 'extension/**'
defaults:
  run:
    working-directory: extension
jobs:
  extension-checks:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
          cache-dependency-path: extension/yarn.lock
      - run: yarn install --immutable
      - name: Lint
        run: yarn lint
      - name: Format Check
        run: yarn format-check
      - name: Type Check
        run: yarn type-check
      - name: Unit Tests
        run: yarn test:unit
      - name: Integration Tests
        run: yarn test:integration
      - name: Build
        run: yarn build:ci
      - name: Install Playwright Browser
        run: yarn playwright install --with-deps chromium
      - name: End-to-End Tests
        run: xvfb-run yarn test:e2e
  extension-macos-e2e:
    runs-on: macos-latest
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
          cache-dependency-path: extension/yarn.lock
      - run: yarn install --immutable
      - name: Build
        run: yarn build:ci
      - name: Install Playwright Browser
        run: yarn playwright install --with-deps chromium
      - name: End-to-End Tests (macOS)
        run: yarn test:e2e
