name: Extension Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/extension/**'
      - 'packages/shared/**'
      - '.github/workflows/extension-ci.yml'
defaults:
  run:
    working-directory: apps/extension
jobs:
  extension-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - run: yarn install --immutable
      - name: Lint
        run: yarn lint
      - name: Type Check
        run: yarn type-check
      - name: Unit Tests
        run: yarn extension-test-unit
        working-directory: ${{ github.workspace }}
      - name: Integration Tests
        run: yarn test:integration
      - name: Build
        run: yarn extension-build:ci
        working-directory: ${{ github.workspace }}
      - name: Install Playwright Browser
        run: yarn playwright install --with-deps chromium
      - name: End-to-End Tests
        run: xvfb-run yarn test:e2e
  extension-macos-e2e:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - run: yarn install --immutable
      - name: Build
        run: yarn extension-build:ci
        working-directory: ${{ github.workspace }}
      - name: Install Playwright Browser
        run: yarn playwright install --with-deps chromium
      - name: End-to-End Tests (macOS)
        run: yarn test:e2e
