name: Deploy to Production Firebase Hosting
on:
  push:
    branches:
      - main
    paths:
      - "firebase/hosting/**"
      - ".github/workflows/firebase-hosting-prod.yml"
permissions:
  checks: write
  contents: read
jobs:
  deploy-prod-firebase-hosting:
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: apps/firebase
    env:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZERO_IN_PROD }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - run: yarn install --immutable
      - run: yarn build-hosting
        env:
          VITE_FIREBASE_API_KEY: ${{ vars.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ vars.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ vars.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ vars.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ vars.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ vars.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ vars.VITE_FIREBASE_MEASUREMENT_ID }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          channelId: live
          firebaseServiceAccount: ${{ env.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{ vars.VITE_FIREBASE_PROJECT_ID }}
          entryPoint: firebase
          target: ${{ vars.VITE_FIREBASE_PROJECT_ID }}
