on:
  push:
    branches: [main]
name: Staging Release
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    environment: prod
    env:
      NAME_SUFFIX: ' (STAGING)'
      TAG_NAME: staging
      VITE_FIREBASE_AUTH_DOMAIN: ${{ vars.VITE_FIREBASE_AUTH_DOMAIN }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock
      - run: yarn install --immutable
      - name: Zip
        run: yarn zip
      - name: Delete previous tag # This step is to remove the source code asset of the previous release. Otherwise, they will be included in the new release.
        run: gh release delete ${{env.TAG_NAME}} --cleanup-tag
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: dist/zero-in-${{ env.TAG_NAME }}-chrome.zip
          prerelease: true
          fail_on_unmatched_files: true
